/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GamesRouteImport } from './routes/games'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesCountingIndexRouteImport } from './routes/games.counting.index'
import { Route as GamesBalloonIndexRouteImport } from './routes/games.balloon.index'

const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCountingIndexRoute = GamesCountingIndexRouteImport.update({
  id: '/counting/',
  path: '/counting/',
  getParentRoute: () => GamesRoute,
} as any)
const GamesBalloonIndexRoute = GamesBalloonIndexRouteImport.update({
  id: '/balloon/',
  path: '/balloon/',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRouteWithChildren
  '/games/balloon': typeof GamesBalloonIndexRoute
  '/games/counting': typeof GamesCountingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesRouteWithChildren
  '/games/balloon': typeof GamesBalloonIndexRoute
  '/games/counting': typeof GamesCountingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRouteWithChildren
  '/games/balloon/': typeof GamesBalloonIndexRoute
  '/games/counting/': typeof GamesCountingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games' | '/games/balloon' | '/games/counting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games' | '/games/balloon' | '/games/counting'
  id: '__root__' | '/' | '/games' | '/games/balloon/' | '/games/counting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRoute: typeof GamesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/counting/': {
      id: '/games/counting/'
      path: '/counting'
      fullPath: '/games/counting'
      preLoaderRoute: typeof GamesCountingIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/balloon/': {
      id: '/games/balloon/'
      path: '/balloon'
      fullPath: '/games/balloon'
      preLoaderRoute: typeof GamesBalloonIndexRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesBalloonIndexRoute: typeof GamesBalloonIndexRoute
  GamesCountingIndexRoute: typeof GamesCountingIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesBalloonIndexRoute: GamesBalloonIndexRoute,
  GamesCountingIndexRoute: GamesCountingIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRoute: GamesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
